const reels = [
  {
    username: "alex_coder",
    likeCount: 12450,
    isLiked: false,
    commentCount: 342,
    caption: "Late night coding hits different 💻🌙",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/men/11.jpg",
    shareCount: 120,
    isFollowed: false,
  },
  {
    username: "sophia.designs",
    likeCount: 28900,
    isLiked: true,
    commentCount: 870,
    caption: "Minimal UI > Everything ✨",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/women/21.jpg",
    shareCount: 410,
    isFollowed: true,
  },
  {
    username: "rahul.dev",
    likeCount: 18340,
    isLiked: false,
    commentCount: 455,
    caption: "JavaScript makes life easier 🔥",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/men/35.jpg",
    shareCount: 290,
    isFollowed: true,
  },
  {
    username: "emily.travels",
    likeCount: 45210,
    isLiked: true,
    commentCount: 1320,
    caption: "Mountains > Beaches ⛰️",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/women/44.jpg",
    shareCount: 890,
    isFollowed: false,
  },
  {
    username: "daniel.fitness",
    likeCount: 9780,
    isLiked: false,
    commentCount: 210,
    caption: "Consistency beats motivation 💪",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/men/52.jpg",
    shareCount: 150,
    isFollowed: false,
  },
  {
    username: "priya.art",
    likeCount: 26700,
    isLiked: true,
    commentCount: 640,
    caption: "Art speaks louder than words 🎨",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/women/63.jpg",
    shareCount: 520,
    isFollowed: true,
  },
  {
    username: "mark.music",
    likeCount: 31600,
    isLiked: false,
    commentCount: 910,
    caption: "Music is my escape 🎧",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/men/67.jpg",
    shareCount: 760,
    isFollowed: false,
  },
  {
    username: "neha.foodie",
    likeCount: 22890,
    isLiked: true,
    commentCount: 505,
    caption: "Street food supremacy 🌮🔥",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/women/71.jpg",
    shareCount: 430,
    isFollowed: true,
  },
  {
    username: "kevin.tech",
    likeCount: 14120,
    isLiked: false,
    commentCount: 380,
    caption: "Learning something new every day 🚀",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/men/81.jpg",
    shareCount: 260,
    isFollowed: false,
  },
  {
    username: "ananya.life",
    likeCount: 38900,
    isLiked: true,
    commentCount: 1100,
    caption: "Slow mornings & positive vibes ☀️",
    video: "",
    userProfile: "https://randomuser.me/api/portraits/women/90.jpg",
    shareCount: 840,
    isFollowed: true,
  },
];


export default reels;
